### ISSUE TITLE
Not working on Moto G7 Plus.

### ISSUE THREAD

**Issue by Leon422** [MenosGrante/Rekado#56]
The app simply won't react to my Switch being connected. The Moto G7 Plus is supposed to support OTG. I'm using the included type C to type C cable. I'm running Android 9. Not sure what to do.

**Comment by MenosGrante** [comment]
If your device doesn't react to Nintendo Switch connection in most cases it means your device may not support OTG or it was not enabled before connecting device. For example, on OnePlus devices, you have to enable the "OTG Connection" setting in the "Advanced" section of settings and then all should start working properly.

**Comment by ELY3M** [comment]
I know it have been awhile but I have trinket mod in my main switch now and I have another switch without trinket mod.  I was trying to fire up atmosphere on other switch from my S9 phone.  it never opened a popup.  I tried both my version and your version.  I tried changing usb setting. it is not poping up for me :(   I know i have updated my S9 few times since.  I think it have to do with new android updates?

**Comment by ELY3M** [comment]
It was working perfectly for me when I was using it before I put trinket mod in my main switch.  That is why I was thinking that it may be somewhere in the new android updates.

**Comment by ELY3M** [comment]
this made sense.  https://issuetracker.google.com/issues/121435921

**Comment by ELY3M** [comment]
I revoked all usb auths in debugging section.   now rekado is crashing..  I will try to get crash log....

**Comment by ELY3M** [comment]
I found crash here:  


2019-10-16 14:51:13.220 28682-28682/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pavelrekun.rekado, PID: 28682
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pavelrekun.rekado/com.pavelrekun.rekado.services.usb.USBReceiver}: kotlin.TypeCastException: null cannot be cast to non-null type com.pavelrekun.rekado.data.Payload
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3086)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3229)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: kotlin.TypeCastException: null cannot be cast to non-null type com.pavelrekun.rekado.data.Payload
        at com.pavelrekun.rekado.services.payloads.PayloadHelper.find(PayloadHelper.kt:52)
        at com.pavelrekun.rekado.services.usb.USBReceiver.onCreate(USBReceiver.kt:37)
        at android.app.Activity.performCreate(Activity.java:7326)
        at android.app.Activity.performCreate(Activity.java:7317)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3066)

**Comment by ELY3M** [comment]
I had to disable auto payload setting, I am able to start up my test switch now via my phone.
