### ISSUE TITLE
app crashing on S20 phone

### ISSUE THREAD

**Issue by ELY3M** [MenosGrante/Rekado#89]
here is catlog 

2020-12-16 17:35:11.964 10084-10084/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pavelrekun.rekado, PID: 10084
    java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter payload
        at com.pavelrekun.rekado.screens.payload_fragment.PayloadsAdapter$ViewHolder.bind(Unknown Source:2)
        at com.pavelrekun.rekado.screens.payload_fragment.PayloadsAdapter.onBindViewHolder(PayloadsAdapter.kt:27)
        at com.pavelrekun.rekado.screens.payload_fragment.PayloadsAdapter.onBindViewHolder(PayloadsAdapter.kt:16)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3540)
        at android.view.View.measure(View.java:27128)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7340)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:27128)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7340)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.cardview.widget.CardView.onMeasure(CardView.java:260)
        at com.google.android.material.card.MaterialCardView.onMeasure(MaterialCardView.java:159)
        at android.view.View.measure(View.java:27128)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
        at android.view.View.measure(View.java:27128)
        at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onMeasure(SwipeRefreshLayout.java:641)
        at android.view.View.measure(View.java:27128)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7340)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:27128)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:995)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:27128)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7340)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:27128)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7340)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:27128)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7340)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:27128)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7340)

**Comment by ELY3M** [comment]
look into  

at com.pavelrekun.rekado.screens.payload_fragment.PayloadsAdapter.onBindViewHolder(PayloadsAdapter.kt:27)
at com.pavelrekun.rekado.screens.payload_fragment.PayloadsAdapter.onBindViewHolder(PayloadsAdapter.kt:16)
